[project]
name = "yt-dlp-gui"
dynamic = ["version"]
description = "GUI for downloading video based on yt-dlp and PySide6"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.11.0",
    "pyyaml>=6.0.3",
    "yt-dlp>=2026.3.17",
    "yt-dlp-ejs==0.8.0",
]

[project.scripts]
yt-dlp-gui = "main:main"

[build-system]
requires = ["setuptools==84.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "app.version.VERSION"}

[tool.setuptools.packages.find]
include = ["app*", "core*", "configs*", "gui*", "models*", "services*", "i18n*"]

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.package-data]
configs = ["*.yml"]
gui = ["styles/*.qss"]
i18n = ["*.json"]
